services:
  nginx:
    #image: kevindps06/oei-flow-platform-frontend
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      #- NODE_ENV=preproduction
      #- NODE_ENV=production