import { FileItem } from './FileItem';

export interface FormsJuridica {
  Id: string;
  TipoProceso: string;
  TipoAdquisicion: string;
  TipoAdquisicionOtro?: string;
  TipoPersona: string;
  ConvenioResponsable: string;
  Email: string;
  JustificacionContratacion: string;
  ObjetivoContratacion: string;
  EspecificacionesTecnicasMinimas?: string;
  PerfilRequerido?: string;
  FactoresEvaluacion?: string;
  Objeto: string;
  ObligacionesEspecificas: string;
  ProductosEntregables: string;
  PresupuestoEstimado: string;
  FormaPago: string;
  Plazo: string;
  ManejoDatos: string;
  CategoriaInteresado?: string;
  CategoriaDatosSensibles?: boolean;
  CategoriaDatosIdentificativos?: boolean;
  CategoriaDatosCaracteristicasPersonales?: boolean;
  CategoriaDatosCaracteristicasCircunstanciasSociales?: boolean;
  CategoriaDatosCaracteristicasDetallesEmpleo?: boolean;
  CategoriaDatosEconomicosFinancierosSeguros?: boolean;
  cedulaCiudadaniaFiles?: FileItem[];
  RUTFiles?: FileItem[];
  certificacionBancariaFiles?: FileItem[];
  constanciaAfiliacionSaludFiles?: FileItem[];
  constanciaAfiliacionPensionFiles?: FileItem[];
  constanciaArlFiles?: FileItem[];
  tarjetaProfesionalFiles?: FileItem[];
  hojaVidaFiles?: FileItem[];
  soportesHojaVidaFiles?: FileItem[];
  justificacionContratacionFiles?: FileItem[];
  cotizacionOfertaFiles?: FileItem[];
  informeTecnicoFiles?: FileItem[];
  cuadroComparativoFiles?: FileItem[];
  InformacionAdicional: string;
  Requestor: any;
}
